#
# SPDX-FileCopyrightText: 2024 INFO
# SPDX-License-Identifier: EUPL-1.2+
#

[versions]
detekt = "1.23.8"
kotlin = "2.3.10"
jaxb-api = "2.3.1"
jaxb-impl = "4.0.6"
xjc = "1.9.0"
oss-iban = "1.16.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
jaxb-api = { module = "javax.xml.bind:jaxb-api", version.ref = "jaxb-api" }
jaxb-core = { module = "org.glassfish.jaxb:jaxb-core", version.ref = "jaxb-impl" }
jaxb-runtime = { module = "org.glassfish.jaxb:jaxb-runtime", version.ref = "jaxb-impl" }
oss-iban = { module = "nl.garvelink.oss:iban", version.ref = "oss-iban" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
xjc = { id = "com.github.bjornvester.xjc", version.ref = "xjc" }

